try {                 } catch     { println("error");               }
try {                 } catch err { println("error: " + repr(err)); }
try { 1 + 1;          } catch     { println("error");               }
try { 1 + "foo";      } catch err { println("error: " + repr(err)); }
try { error "oopsie"; } catch err { println("error: " + repr(err)); }
################################################################################
# error: "attempted + operation with types `number` and `string`"
# error: "oopsie"
